apiVersion: v1
kind: ConfigMap
metadata:
  name: pqr-genai-conf
data:
  SSL_VERIFY: "true"
  OPENSEARCH_ENDPOINT: "https://opensearch.pqr-genai.svc.cluster.local:9200"
  OPENSEARCH_VERIFY_SSL: "false"
  OPENSEARCH_CONVERSATIONS_INDEX: "conversations-reference"
  OPENSEARCH_MESSAGES_INDEX: "conversations-messages"
  OPENSEARCH_TIMEOUT: "10"
